drop table if exists person;

create table person
(
	id int primary key generated by default as identity, 
	externalid uuid not null unique default gen_random_uuid (),
	title varchar(2000) null,
	legalname varchar(4000) not null,
	preferredname varchar(4000) null,
	alias varchar(50) not null unique,
	primaryemailaddress varchar(320) not null unique,
	createdby int not null default 0,
	createddate timestamp with time zone not null default now(),
	modifiedby int not null default 0,
	modifieddate timestamp with time zone not null default now()
);
